
FROM bde2020/spark-master:3.1.1-hadoop3.2

# Install Python dependencies required for Spark MLlib
RUN apk update && \
    apk add --no-cache \
    py3-numpy \
    py3-requests

# Set working directory
WORKDIR /spark
